project17/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insert_Dept/', insert_Dept, name='insert_Dept'),
    path('insert_Emp/', insert_Emp, name='insert_Emp'),
    path('displayDept/', displayDept, name='displayDept'),
    path('displayEmp/', displayEmp, name='displayEmp'),
    path('empdept/', empdept, name='empdept'),
    path('empmgr/', empmgr, name='empmgr'),
    path('empdeptmgr/', empdeptmgr, name='empdeptmgr'),
    path('deptemp/', deptemp, name='deptemp'),

]

app/models.py
from django.db import models

# Create your models here.
class Dept(models.Model):
    deptno=models.IntegerField(primary_key=True)
    dname=models.CharField(max_length=100)
    dloc=models.CharField(max_length=100)
    def __str__(self):
        return self.dname



class Emp(models.Model):
    empno=models.IntegerField(primary_key=True)
    ename=models.CharField(max_length=100)
    job=models.CharField(max_length=100)
    sal=models.DecimalField(max_digits=10, decimal_places=2)
    hiredate=models.DateField(auto_now_add=True)
    mgr=models.ForeignKey('self',on_delete=models.SET_NULL, null=True, blank=True)
    comm=models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    deptno=models.ForeignKey(Dept, on_delete=models.CASCADE)
    def __str__(self):
        return self.ename


class Salgrade(models.Model):
    grade=models.IntegerField(primary_key=True)
    losal=models.DecimalField(max_digits=10, decimal_places=2)
    hisal=models.DecimalField(max_digits=10, decimal_places=2)

templates/deptemp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Prefetch_related</h1>
        {% for DO in LDEO %}
            <h1>dept name:{{DO.dname}}</h1>
           <h1>dept no:{{DO.deptno}}</h1>
           <h1>dept loc:{{DO.dloc}}</h1>
            {% for EO in DO.emp_set.all %}
                <h3>emp name:{{EO.ename}}</h3>
                <h3>emp no:{{EO.empno}}</h3>
                <h3>JOb:{{EO.job}}</h3>
            {% endfor %}
        {% endfor %}
        
    </center>
</body>
</html>

templates/displayDept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            display Dept data
        </h1>
        <table border="3px">
            <tr>
                <th>
                    deptno
                </th>
                <th>dname</th>
                <th>dloc</th>
            </tr>
            {% for do in depts %}
                <tr>
                    <td>{{ do.deptno }}</td>
                    <td>{{ do.dname }}</td>
                    <td>{{ do.dloc }}</td>

                </tr>
            {% endfor %}
             
        </table>
    </center>
</body>
</html>

templates/displayEmp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>display Emp data</h1>
        <table border="3px">
            <tr>
                <!-- <th>pk/id</th> -->
                <!-- <th>deptno</th>
                <th>dname</th>
                <th>dloc</th> -->
                <td>empno</td>
                <td>ename</td>
                <th>job</th>
                <th>sal</th>
                <th>hireddate</th> 
                <th>mgr</th>
                <th>comm</th>
                <th>deptno</th>
                <th>dname</th>
                <th>dloc</th>
            </tr>
            {% for eo in emps %}
                <tr>

                    <!-- <td>{{ do.deptno }}</td>
                    <td>{{ do.dname }}</td>
                    <td>{{ do.dloc }}</td>  -->



                    <!-- <td>{{eo.id}}</td> -->
                    <td>{{ eo.empno }}</td>
                    <td>{{ eo.ename }}</td>
                    <td>{{ eo.job }}</td>
                    <td>{{ eo.sal }}</td>
                    <td>{{ eo.hiredate }}</td> 
                    <td>{{ eo.mgr }}</td>
                    <td>{{ eo.comm }}</td>
                    <td>{{ eo.deptno }}</td>
                    <td>{{ eo.deptno.dname }}</td>
                    <td>{{ eo.deptno.dloc }}</td>


                </tr>
            {% endfor %}
        </table>
    </center>
</body>
</html>

templates/empdept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>JOining of tables</h1>
        <table border="3px">
            <tr>
                <th>empno</th>
                <th>ename</th>
                <th>job</th>
                <th>sal</th>
                <th>comm</th>
                <th>mgr</th>
                <th>deptno</th>
                <th>dname</th>
                <th>dloc</th>
            </tr>

            {% for eo in emps  %}
            <tr>
                <td>{{eo.empno}}</td>
                <td>{{eo.ename}}</td>
                <td>{{eo.job}}</td>
                <td>{{eo.sal}}</td>
                <td>{{eo.comm}}</td>
                <td>{{eo.mgr}}</td> 
                <td>{{eo.deptno}}</td>
                <td>{{eo.deptno.dname}}</td>
                <td>{{eo.deptno.dloc}}</td>



            </tr>
            {% endfor %}
        </table>
    </center>
</body>
</html>

templates/empdeptmgr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Emp Mgr data</h1>
        <table border="5px">
            <tr>
                <th>empno</th>
                <th>Ename</th>
                <th>eJob</th>
                <th>sal</th>
                <th>ecomm</th>
                <th>deptno</th>
                <th>managername</th>
                <th>managersal</th>
                <th>managerjob</th>
                <th>managercomm</th>
                <th>deptname</th>
            </tr>
            {% for edmo in LEDMO %}
            <tr>
                <td>{{edmo.empno}}</td>
                <td>{{edmo.ename}}</td>
                <td>{{edmo.job}}</td>
                <td>{{edmo.sal}}</td>
                <td>{{edmo.comm}}</td>
                <td>{{edmo.deptno}}</td>

                <td>{{edmo.mgr.ename}}</td>
                <td>{{edmo.mgr.sal}}</td>
                <td>{{edmo.mgr.job}}</td>
                <td>{{edmo.mgr.comm}}</td>
                <td>{{edmo.deptno.dname}}</td>




            </tr>
            {% endfor %}
        </table>
    </center>
</body>
</html>

templates/empmgr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Emp Mgr data</h1>
        <table border="5px">
            <tr>
                <th>empno</th>
                <th>Ename</th>
                <th>eJob</th>
                <th>sal</th>
                <th>ecomm</th>
                <th>deptno</th>
                <th>managername</th>
                <th>managersal</th>
                <th>managerjob</th>
                <th>managercomm</th>
            </tr>
            {% for emo in LEMO %}
            <tr>
                <td>{{emo.empno}}</td>
                <td>{{emo.ename}}</td>
                <td>{{emo.job}}</td>
                <td>{{emo.sal}}</td>
                <td>{{emo.comm}}</td>
                <td>{{emo.deptno}}</td>

                <td>{{emo.mgr.ename}}</td>
                <td>{{emo.mgr.sal}}</td>
                <td>{{emo.mgr.job}}</td>
                <td>{{emo.mgr.comm}}</td>




            </tr>
            {% endfor %}
        </table>
    </center>
</body>
</html>